OPENNSL_VERSION = 3.5.0.3

export OPENNSL_VERSION

BRCM_LIBOPENNSL = libopennsl_$(OPENNSL_VERSION)_amd64.deb
$(BRCM_LIBOPENNSL)_SRC_PATH = $(SRC_PATH)/opennsl
SONIC_DPKG_DEBS += $(BRCM_LIBOPENNSL)

# Implicitly. BRCM_OPENNSL_KERNEL and BRCM_LIBOPENNSL_DEV is compiled with BRCM_LIBOPENNSL together
BRCM_OPENNSL_KERNEL = opennsl-modules-3.16.0-5-amd64_$(OPENNSL_VERSION)_amd64.deb
$(BRCM_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(eval $(call add_derived_package,$(BRCM_LIBOPENNSL),$(BRCM_OPENNSL_KERNEL)))

BRCM_LIBOPENNSL_DEV = libopennsl-dev_$(OPENNSL_VERSION)_amd64.deb
$(eval $(call add_derived_package,$(BRCM_LIBOPENNSL),$(BRCM_LIBOPENNSL_DEV)))
